# Generated by Django 2.2.16 on 2022-07-16 09:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myownuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('6be7a4b5-d943-410a-b1a1-6078cde4d162'), max_length=60),
        ),
    ]
