# Generated by Django 2.2.16 on 2022-07-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220716_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myownuser',
            old_name='confirmation_code',
            new_name='conf_code',
        ),
    ]
