# Generated by Django 2.2.16 on 2022-07-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_title_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myownuser',
            old_name='conf_code',
            new_name='conformation_code',
        ),
    ]
