# Generated by Django 2.2.16 on 2022-07-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220717_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myownuser',
            old_name='conformation_code',
            new_name='confirmation_code',
        ),
    ]
