# Generated by Django 2.2.16 on 2022-07-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220717_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'Объект творчества', 'verbose_name_plural': 'Объекты творчества'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
